server:
  port: 8089
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
pascucci:
  client:
    address:
      url: http://localhost:8082/addresses
    vehicle:
      url: http://localhost:8084/chassis